###########################################
# Database configuration
###########################################
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/booking?serverTimezone=UTC&characterEncoding=UTF-8
    username: develop
    password: develop!@

###########################################
# JPA configuration
###########################################
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging.level.org.hibernate.SQL: DEBUG
server:
  port: 8080
  shoutdown: graceful
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

