###백오피스 API 목록
###1. 강의 등록
POST http://localhost:8080/lecture
Content-Type: application/json

{
  "speaker":"김성수",
  "place":"대회의실",
  "capacity":300,
  "startDateTime":"2023-09-15 17:00:00",
  "contents":"키다리스튜디오의 성장과 발전"
}

###2. 강의 조회 단건/전체
GET http://localhost:8080/lecture

###3. 강의 단건 조회
GET http://localhost:8080/lecture?name=슈퍼
